### PR TITLE
Update list of tasks

### PR DESCRIPTION
**Pull request by zeGihon**
Updating on the list tasks. Found this interesting and appended on the list of the machine learning algorithms.

### CODE REVIEW

**Comment by nahomm** [comment]
It is a good list. Bravo!

**Comment by nahomm** [comment]
``` C#
using System;
public class Appreciation
{
    public static void Main()
    {
         Console.WriteLine("Bravo!!!");
    }
}
```

**Comment by zeGihon** [comment]
I am closing the thread. The bug is fixed. What do you think?

**Comment by nahomm** [comment]
I also think that it should be closed. You can close the thread.

**Comment by zeGihon** [comment]
Ok, good. Closing.

**Pull request merged**
